---
apiVersion: v1
kind: Service
metadata:
  name: configdb-service
  namespace: mongodb
  labels:
    svc: configdb
spec:
  ports:
  - port: 9281
    targetPort: 9281
  clusterIP: None
  selector:
    app: config-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: configdb
  namespace: mongodb
  labels:
    app: config-server
    cluster: configdb
spec:
  serviceName: configdb-service
  replicas: 3
  selector:
    matchLabels:
      app: config-server
      cluster: configdb  
  template:
    metadata:
      labels:
        app: config-server
        cluster: configdb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: cluster
                    operator: In
                    values:
                    - configdb
                topologyKey: kubernetes.io/hostname
      serviceAccountName: mongo-admin
      terminationGracePeriodSeconds: 21
      containers:
        - name: mongodb-cluster-configdb
          image: mongo
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.2
              memory: 100Mi
            limits:
              cpu: 0.7
              memory: 1Gi
          volumeMounts:
          - name: config-volume
            mountPath: /etc/configdb.conf
            subPath: configdb.conf
          - name: configdb-data
            mountPath: /data/db
          #workingDir: /data
          command:
            - "mongod"
            - "-f"
            - "/etc/configdb.conf"
          ports:
            - name: configdb-port
              containerPort: 9281
          #livenessProbe:
          #  tcpSocket:
          #    port: cfgsvr-port
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 90
          #  periodSeconds: 60
          #readinessProbe:
          #  exec:
          #    command:
          #      - mongo
          #      - --eval
          #      - "db.adminCommand('ping')"
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 90
          #  periodSeconds: 60
      restartPolicy: Always
      volumes:  
      - name: config-volume
        configMap:
          name: configdb-config
          items:
          - key: configdb.conf
            path: configdb.conf
  volumeClaimTemplates:
  - metadata:
      name: configdb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block 
      resources:
        requests:
          storage:  33Gi
