---
apiVersion: v1
kind: Service         
metadata:
  name: shard2-service
  namespace: mongodb
  labels:
    srv: shard2
spec:
  ports:
  - port: 9002
    targetPort: 9002
  clusterIP: None     
  selector:
    app: shard2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard2
  namespace: mongodb
  labels:
    app: shard2
    cluster: shard
spec:
  serviceName: shard2-service
  replicas: 1
  selector:
    matchLabels:
      app: shard2
      cluster: shard   
  template:
    metadata:
      labels:
        app: shard2
        cluster: shard
    spec:
      affinity:         
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:    
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: cluster
                    operator: In
                    values:
                    - shard
                topologyKey: kubernetes.io/hostname           
      serviceAccountName: mongo-admin
      terminationGracePeriodSeconds: 21
      containers:
        - name: mongodb-cluster-shard2
          image: mongo
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.5
              memory: 200Mi
            limits:
              cpu: 1.5
              memory: 2Gi
          volumeMounts:
          - name: config-volume
            mountPath: /etc/shard2.conf
            subPath: shard2.conf         
          - name: shard2-data
            mountPath: /data/db
          #workingDir: /data
          command:
            - "mongod"
            - "-f"
            - "/etc/shard2.conf"
          ports:
            - name: shard2-port
              containerPort: 9002
          #livenessProbe:
          #  tcpSocket:
          #    port: shard2-port
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 90
          #  periodSeconds: 60
          #readinessProbe:           
          #  exec:
          #    command:
          #      - mongo
          #      - --eval
          #      - "db.adminCommand('ping')"
          #  initialDelaySeconds: 60
          #  timeoutSeconds: 90
          #  periodSeconds: 60
      restartPolicy: Always
      volumes:  
      - name: config-volume
        configMap:
          name: shard-config
          items:
          - key: shard2.conf
            path: shard2.conf
  volumeClaimTemplates:
  - metadata:
      name: shard2-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block 
      resources:
        requests:
          storage:  100Gi