---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
  labels:
    ns: mongodb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-admin
  namespace: mongodb
  labels:
    scop: namespace-mongodb
    desc: mongodb-cluster-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: mongodb-cluster-role
  namespace: mongodb
  labels:
    scop: namespace-mongodb
    desc: nsadmin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - pods
  - podtemplates
  - replicationcontrollers
  - secrets
  - services
  verbs:
  - "*"
- apiGroups:
  - apps 
  resources:
  - daemonsets
  - deployments
  - replicasetes
  - statefulsets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cluster-common-role
  labels:
    scop: global
    desc: resource-scheduling
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - pods
  - podtemplates
  - replicationcontrollers
  - secrets
  - services
  - nodes
  - nodes/proxy
  - persistentvolumes
  - persistentvolumeclaims
  - endpoints
  verbs:
  - "*"
- apiGroups:
  - apps 
  resources:
  - daemonsets
  - deployments
  - replicasetes
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - rook.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mongodb-role-binding
  namespace: mongodb
  labels:
    scop: namespace-mongodb
    desc: mongodb-cluster-account
subjects:
- kind: ServiceAccount
  name: mongo-admin
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mongodb-cluster-role-binding
  namespace: mongodb
  labels:
    scop: namespace_mongodb
    desc: mongodb-cluster-account
subjects:
- kind: ServiceAccount
  name: mongo-admin
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-common-role