apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2019-09-05T15:46:12Z
  name: kafka-cluster-config
  namespace: kafka
data:
  zookeeper.conf: |
    dataDir=/data
    clientPort=17690
    maxClientCnxns=100
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=true
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=1
  kafka.conf: |
    broker.id=0
    port=18956
    listeners=PLAINTEXT://0.0.0.0:18956
    advertised.listeners=PLAINTEXT://0.0.0.0:18956
    log.dirs=/data
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/var/log/kafka.log
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=zookeeper-0.zookeeper-service.kafka.svc.cluster.local:17690
    zookeeper.connection.timeout.ms=6000
    group.initial.rebalance.delay.ms=0
    log.cleaner.enable=true
    log.cleanup.policy=delete
    log.retention.hours=24
    log.retention.check.interval.ms=180000
    log.retention.bytes=1073741824