---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    ns: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-admin
  namespace: redis
  labels:
    scop: namespace-redis
    desc: redis-cluster-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: redis-cluster-role
  namespace: redis
  labels:
    scop: namespace-redis
    desc: nsadmin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - pods
  - podtemplates
  - replicationcontrollers
  - secrets
  - services
  verbs:
  - "*"
- apiGroups:
  - apps 
  resources:
  - daemonsets
  - deployments
  - replicasetes
  - statefulsets
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redis-role-binding
  namespace: redis
  labels:
    scop: namespace-redis
    desc: redis-cluster-account
subjects:
- kind: ServiceAccount
  name: redis-admin
  namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-cluster-role-binding
  namespace: redis
  labels:
    scop: namespace_redis
    desc: redis-cluster-account
subjects:
- kind: ServiceAccount
  name: redis-admin
  namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-common-role